package settings

import (
	"bytes"
	"fmt"
	"strings"
)

// Markdown returns the settings reference, docs/settings.md: per section a
// table of every setting with its English label and description, default,
// unit, range or values, restart flag and overrides, then the why of each
// setting. theserver settings doc writes it.
func Markdown() []byte {
	var buf bytes.Buffer
	buf.WriteString(`# Settings

Generated by ` + "`theserver settings doc`" + ` from the settings registry in ` + "`internal/settings`" + ` (D-030). Do not edit this file by hand; a test fails when it differs from what the command writes.

Every setting can be set in the configuration file, by an environment variable or by a flag where one exists. Precedence, highest first: command line flags, environment variables, the configuration file, built in defaults. On the admin page and through ` + "`PUT /api/v1/settings`" + ` a change is written to the configuration file the server was started with (D-032). A setting marked restart takes effect when theserver starts again, every other one at once. The admin page shows the same texts in English and German (D-031).
`)
	for _, section := range Sections() {
		if !bytes.HasSuffix(buf.Bytes(), []byte("\n\n")) {
			buf.WriteString("\n")
		}
		fmt.Fprintf(&buf, "## %s\n\n", section)
		buf.WriteString("| Setting | Label | Description | Default | Unit | Range or values | Restart | Environment | Flag |\n")
		buf.WriteString("| --- | --- | --- | --- | --- | --- | --- | --- | --- |\n")
		for _, s := range registry {
			if s.Section != section {
				continue
			}
			text := s.TextIn(FallbackLanguage)
			restart := "no"
			if s.Restart {
				restart = "yes"
			}
			flag := ""
			if s.Flag != "" {
				flag = "`--" + s.Flag + "`"
			}
			fmt.Fprintf(&buf, "| `%s` | %s | %s | %s | %s | %s | %s | `%s` | %s |\n",
				s.Key, cell(text.Label), cell(text.Description), defaultCell(s), s.Unit, rangeCell(s), restart, s.Env(), flag)
		}
		buf.WriteString("\n")
		for _, s := range registry {
			if s.Section != section {
				continue
			}
			text := s.TextIn(FallbackLanguage)
			fmt.Fprintf(&buf, "**%s** (`%s`). %s\n\n", cell(text.Label), s.Key, text.Why)
		}
	}
	return append(bytes.TrimRight(buf.Bytes(), "\n"), '\n')
}

func cell(text string) string {
	return strings.ReplaceAll(text, "|", "\\|")
}

func defaultCell(s Setting) string {
	switch v := s.Default.(type) {
	case string:
		if v == "" {
			return "empty"
		}
		return "`" + v + "`"
	default:
		return fmt.Sprintf("`%v`", v)
	}
}

func rangeCell(s Setting) string {
	switch {
	case s.Min != nil && s.Max != nil:
		return fmt.Sprintf("%d to %d", *s.Min, *s.Max)
	case len(s.Enum) > 0:
		return "`" + strings.Join(s.Enum, "`, `") + "`"
	case s.Empty:
		return "may be empty"
	}
	return ""
}
